# Generated by Django 4.2.11 on 2025-06-13 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_account', '0002_alter_notification_notice_for'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='category',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='notice_for',
        ),
        migrations.DeleteModel(
            name='NoticeCategory',
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
