# Generated by Django 4.2.11 on 2025-01-16 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_chat', '0002_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='timestamp',
        ),
    ]
