# Generated by Django 4.2.11 on 2025-01-17 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_chat', '0003_remove_message_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
