# Generated by Django 4.2.11 on 2025-06-07 10:09

import core.settings.content_path
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0005_profile_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='cover_photo',
            field=models.ImageField(blank=True, default='cover.png', null=True, upload_to=core.settings.content_path.UserContentPath('cover_pic')),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='default.png', upload_to=core.settings.content_path.UserContentPath('profile_pictures')),
        ),
    ]
