# Generated by Django 4.2.11 on 2025-06-07 10:09

import core.settings.content_path
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_home', '0011_friends_privacy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postimage',
            name='image',
            field=models.ImageField(upload_to=core.settings.content_path.UserContentPath('post_images', include_date=True)),
        ),
        migrations.AlterField(
            model_name='story',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=core.settings.content_path.UserContentPath('stories', include_date=True)),
        ),
    ]
