# Generated by Django 4.2.11 on 2025-06-07 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0006_alter_profile_cover_photo_and_more'),
        ('app_home', '0012_alter_postimage_image_alter_story_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='postimage',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post_images', to='app_users.profile'),
        ),
    ]
