# Generated by Django 4.2.11 on 2025-06-13 06:24

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_users', '0007_profile_access_token_profile_display_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NoticeCategory',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(choices=[('friennd_request', 'friend_request'), ('message', 'message'), ('mention', 'mention'), ('like', 'like'), ('comment', 'comment'), ('follow', 'follow'), ('other', 'other')], max_length=70, unique=True)),
                ('yes_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notification', models.CharField(max_length=150)),
                ('link', models.URLField(blank=True, max_length=500, null=True)),
                ('seen', models.BooleanField(default=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notice', to='app_notification.noticecategory')),
                ('notice_for', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='app_users.profile')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
