# Generated by Django 4.2.11 on 2025-06-13 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_notification', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticecategory',
            name='name',
            field=models.CharField(choices=[('friend_request', 'friend_request'), ('message', 'message'), ('mention', 'mention'), ('like', 'like'), ('comment', 'comment'), ('follow', 'follow'), ('other', 'other')], max_length=70, unique=True),
        ),
    ]
