# Generated by Django 4.2.11 on 2025-06-13 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_notification', '0002_alter_noticecategory_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='content',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
